"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
# A minimal left prompt
format = '$directory$git_branch$git_status$character'
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
#right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = '[❮](bold flamingo)'
success_symbol = '[❯](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
symbol = ''
always_show_remote = true
style = 'bold mauve'
truncation_length = 7
truncation_symbol = ''
format = '[[$symbol ](bold green)$branch(:[$remote_branch](bold purple))]($style)'

[git_status]
disabled = false
style = 'bold mauve'
conflicted = '[](bold red)'
ahead = '[](bold red)'
diverged = '󰧈${ahead_count}${behind_count}'
behind = '[](bold yellow)'
untracked = '[ ${count}](red)'
stashed = '[ 󰆧](bold $style)'
modified = '[ ${count}](bold maroon)'
staged = '[ ($count)](bold green)'
renamed = ' 󰑇'
deleted = '[ 󰛉${count}](bold red)'
up_to_date = '[](bold green)'
format = '[ [](overlay1)($all_status) [$stashed](bold yellow)$ahead_behind]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
